### ISSUE TITLE
[Feature request] let users skip mnemonic backup on testnet

### ISSUE THREAD

**Issue by torkelrogstad** [Blockstream/green_ios#18]
It'd be great if I didn't have to backup my mnemonic on testnet. In general, the UX where the app prompts you for backing up even before you have any money at all is very frustrating. Why bother the user with this if they are only going to have a few thousand sats on the app?

**Comment by alessandro-saglimbeni** [comment]
Testnet exists for users to test without risks every feature, including the onboarding procedure, so that they know what they will be required to do when setting up their bitcoin wallet.

The onboarding procedure requires users to backup their mnemonic at the very beginning, bacause Green is a non-custodial wallet, and the mnemonic is your ultimate anchor to get hold of your funds, therefore we have no means to help users if they lost their mnemonic backup.

Asking the user to backup the mnemonic after creating the wallet, for instance before they try to generate an addess to receive could be even worse, as the user might find himself blocked while trying to receive some funds, which is even more frustrating.

The lion share of the support requests, are from users who lost access to their wallet because they didn't properly backup their 2FA (which we don't require users to backup, but remind via notifications to activate more than one 2FA), and/or they didn't backup thei mnemonic despite forcing them to do the backup procedure.

**Comment by torkelrogstad** [comment]
Thanks for replying! I don't agree with your decision, but I understand your reasoning. Keep up the good work on this great wallet!
